function dGamma_dw = dGammadW(b,mu_0,sigma,v_x,v_y,w_e,xi)
%DGAMMADW
%    DGAMMA_DW = DGAMMADW(B,MU_0,SIGMA,V_X,V_Y,W_E,XI)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    31-Oct-2014 17:50:13

t2 = xi.^2;
t3 = w_e.*1i;
t4 = v_x.*xi.*1i;
t5 = t3+t4;
t6 = mu_0.*sigma.*t5;
t7 = mu_0.^2;
t8 = sigma.^2;
t9 = v_y.^2;
t10 = t7.*t8.*t9.*(1.0./4.0);
t11 = t2+t6+t10;
t12 = sqrt(t11);
t13 = b.*t12;
t14 = coth(t13);
t15 = t2.*2.0;
t16 = t12.*t14.*xi.*2.0;
t17 = t6+t15+t16;
dGamma_dw = (mu_0.*sigma.*1i)./t17-mu_0.*sigma.*1.0./t17.^2.*(t3+t4-v_y.*xi).*(mu_0.*sigma.*1i+mu_0.*sigma.*1.0./sqrt(t11).*t14.*xi.*1i-b.*mu_0.*sigma.*xi.*(t14.^2-1.0).*1i);
