classdef InspectorGenerator
    %UNTITLED2 Summary of this class goes here
    %   Detailed explanation goes here
    
    
    
    methods
        function obj = InspectorGenerator(varargin)
        end
        function obj = addCoupler(obj,axis, d)
        end
        function obj = genFile(obj,file_name)
            fileID = fopen(file_name,'w');
            fprintf(fileID,obj.top);
            fprintf(fileID,obj.base_link);
            for i=1:obj.num_couplers
                obj.max_coupler_id = obj.max_coupler_id + 1;
                fprintf(fileID,obj.coupler_joint,obj.max_coupler_id,obj.max_coupler_id);
                fprintf(fileID,obj.coupler,obj.max_coupler_id,obj.max_coupler_id);
                fprintf(fileID,obj.coupler_link,obj.max_coupler_id);
            end
            fprintf(fileID,obj.bottom);
        end
    end
    
    
    
    properties
        num_couplers = 2;
        max_coupler_id = 0;
        filename;
        text;
        top = '<?xml version="1.0" ?>\n <robot name="test_inductor">\n';
        bottom = '</robot>';
        
        base_link = ['<link name="base_link">\n',...
            '<inertial>\n',...
            '<mass value="1"/>\n',...
            '<origin xyz="0 0 0"/>\n',...
            '<inertia ixx="1" ixy="0" ixz="0" iyx="0" iyy="1" iyz="0" izx="0" izy="0" izz="1" />\n',...
            '</inertial>\n',...
            '<visual>\n',...
            '<origin rpy="0 0 0" xyz="0 0 0" />\n',...
            '<geometry>\n',...
            '<box size="0.1 0.1 0.1" />\n',...
            '</geometry>\n',...
            '</visual>\n',...
            '<collision>\n',...
            '<origin rpy="0 0 0" xyz="0 0 0" />\n',...
            '<geometry>\n',...
            '<box size="0.1 0.1 0.1" />\n',...
            '</geometry>\n',...
            '</collision>\n',...
            '</link>\n'];
        
        coupler_joint = ['<joint name="coupler%d_joint" type="continuous">\n',...
            '<origin xyz="0 0.15 0"/>\n',...
            '<axis xyz = "0 1 0" />\n',...
            '<parent link="base_link"/>\n',...
            '<child link="coupler%d_link"/>\n',...
            '</joint>\n'];
        
        coupler = ['<force_element name="coupler%d">\n',...
            '<induction_coupler lower_limit="-10" upper_limit="10" scale_factor_thrust="1.0" scale_factor_moment="0.0245">\n',...
            '<parent link="coupler%d_link"/>\n',...
            '<origin xyz="0 0 0"/>\n',...
            '<axis xyz="0 1 0"/>\n',...
            '</induction_coupler>\n',...
            '</force_element>\n'];
        coupler_link = ['<link name="coupler%d_link">\n',...
            '<inertial>\n',...
            '<mass value="0.01"/>\n',...
            '<origin xyz="0 0 0"/>\n',...
            '<inertia ixx="0.01" ixy="0" ixz="0" iyx="0" iyy="0.01" iyz="0" izx="0" izy="0" izz="0.01" />\n',...
            '</inertial>\n',...
            '<visual>\n',...
            '<origin rpy="0 0 0" xyz="0 0 0" />\n',...
            '<geometry>\n',...
            '<box size="0.05 0.05 0.05" />\n',...
            '</geometry>\n',...
            '</visual>\n',...
            '<collision>\n',...
            '<origin rpy="0 0 0" xyz="0 0 0" />\n',...
            '<geometry>\n',...
            '<box size="0.0 0.0 0.0" />\n',...
            '</geometry>\n',...
            '</collision>\n',...
            '</link>\n']
        
        
    end
end